#ifndef BB_ERROR_HANDLING
#define BB_ERROR_HANDLING

typedef enum BBError
{
    BB_ERROR_OK,
    BB_ERROR_UNKNOWN,
    BB_ERROR_MEM,
    BB_ERROR_DESCRIPTOR_POOL,
    BB_ERROR_DESCRIPTOR,
    BB_ERROR_DESCRIPTOR_SET,
    BB_ERROR_DESCRIPTOR_LAYOUT,
    BB_ERROR_SHADER_MODULE,
    BB_ERROR_PIPELINE_CREATE,
    BB_ERROR_PIPELINE_LAYOUT_CREATE,
    BB_ERROR_IMAGE_CREATE,
    BB_ERROR_IMAGE_VIEW_CREATE,
    BB_ERROR_IMAGE_SAMPLER_CREATE,
    BB_ERROR_IMAGE_LAYOUT_TRANSISTION,
    BB_ERROR_GPU_BUFFER_CREATE,
    BB_ERROR_COMMAND_BUFFER_RECORD,
    BB_ERROR_COMMAND_BUFFER_CREATE,
    BB_ERROR_COMMAND_BUFFER_RUN,
    BB_ERROR_ACQUIRE_SWAP_CHAIN_IMAGE,
    BB_ERROR_TYPE_COUNT // The amount of different errors
}BBError;


#endif
